repos:
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['-i', '--remove-all-unused-imports']
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ['-l', '120']
        
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
        
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [
            '--force-single-line-imports',
            '--profile', 'black'
        ]
        
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [
            '--max-line-length', '120',
            '--max-doc-length', '120',
            '--ignore', 'F821,E402,W503'
        ]
  - repo: https://github.com/Carreau/velin
    rev: 0.0.12
    hooks:
      - id: velin
        name: Velin
        entry: velin
        types: [ python ]
        args: ["--write"]