name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simulation-data-test:
    runs-on: self-hosted
    steps:
      - run: echo $(hostname)
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.7
      
      - name: Install dependencies
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install -e .
          
      - name: Unittests
        run: echo %PATH%
        shell: cmd
      
      - name: Unittest_cmd
        run: cmd.exe /c "C:\actions-runner\_work\optical-automation\optical-automation\scdm_CI.bat"
        shell: cmd
        
        
