name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simulation-data-test:
    runs-on: self-hosted
    steps:
      - run: echo $(hostname)
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8.9
