name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  simulation-data-unittest:
    runs-on: self-hosted
    steps:
      - run: echo "Hello World, test"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
