name: ci
on:
  pull_request:
    branches:
      - main
    paths:
      - ansys_optical_automation/**
      - tests/**
      - .github/**

jobs:
  simulation-data-test:
    runs-on: self-hosted
    steps:
      - run: echo $(hostname)
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      
      - name: Install dependencies
        run: |
          py -3 -m ensurepip
          python -m venv venv
          venv\Scripts\Activate.ps1
          py -3 -m pip install --upgrade pip
          py -3 -m pip install .[test]
          
      - name: Unittests
        run: |
          venv\Scripts\Activate.ps1
          pytest -v tests
