name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  simulation-data-unittest:
    runs-on: self-hosted
    steps:
      - run: echo $(hostname)
      - name: Check out repository code
        uses: actions/checkout@v3
